### ISSUE TITLE
Error upon npm run start

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#156]
## Description

I'm trying to run the `main` branch as a way of testing where another issue might be coming from (see context).

## To Reproduce

```
git clone git@github.com:hypergraph-xyz/desktop
cd desktop
npm install
npm run build
npm run start
```

## Expected behavior

Boots Hypergraph

## Actual behavior

Returns error

```
(node:10738) UnhandledPromiseRejectionWarning: Error: Invalid header: Does not start with Cr24
    at crxToZip (/Users/chjh/git/hypergraph-xyz/desktop/node_modules/unzip-crx/dist/index.js:32:15)
    at /Users/chjh/git/hypergraph-xyz/desktop/node_modules/unzip-crx/dist/index.js:57:32
    at callHanler (/Users/chjh/git/hypergraph-xyz/desktop/node_modules/yaku/lib/yaku.js:719:16)
    at tryCatcher (/Users/chjh/git/hypergraph-xyz/desktop/node_modules/yaku/lib/yaku.js:436:32)
    at /Users/chjh/git/hypergraph-xyz/desktop/node_modules/yaku/lib/yaku.js:575:38
    at flush (/Users/chjh/git/hypergraph-xyz/desktop/node_modules/yaku/lib/yaku.js:478:17)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
(node:10738) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10738) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## System

- OS (incl. version): macOS 10.15.6
- Hypergraph Desktop version: `main`
- Node v12.18.2
- npm 6.14.5

## Additional context

I was trying this to debug another issue where the Hypergraph window doesn't open after booting the app. This is all being run on a clean install of macOS. When I run `npm test` it passes without a hitch.

**Comment by jameslibscie** [comment]
I use the command `npm start` rather than `npm run build` and `npm run start`. Does that work for you?

**Comment by chartgerink** [comment]
Same error, but thanks for the suggestion 😸

**Comment by juliangruber** [comment]
@chartgerink does it still not launch for you?

**Comment by juliangruber** [comment]
Can you try `rm -rf node_modules && npm cache clean -f && npm install`?
