### ISSUE TITLE
Linux AppImage not launching

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#191]
## Description

Cannot launch Hypergraph on Linux

## To Reproduce

```
curl https://github.com/hypergraph-xyz/desktop/releases/download/v0.4.0/Hypergraph-0.4.0.AppImage > Hypergraph-0.4.0.AppImage
chmod +x Hypergraph-0.4.0.AppImage
./Hypergraph-0.4.0.AppImage
```

## Expected behavior

Launch Hypergraph.

## Actual behavior

Error report and no launch.

```
(node:2500) UnhandledPromiseRejectionWarning: Error: Invalid header: Does not start with Cr24
    at crxToZip (/tmp/.mount_HypergwCRUDA/resources/app.asar/node_modules/unzip-crx/dist/index.js:32:15)
    at /tmp/.mount_HypergwCRUDA/resources/app.asar/node_modules/unzip-crx/dist/index.js:57:32
    at callHanler (/tmp/.mount_HypergwCRUDA/resources/app.asar/node_modules/yaku/lib/yaku.js:719:16)
    at tryCatcher (/tmp/.mount_HypergwCRUDA/resources/app.asar/node_modules/yaku/lib/yaku.js:436:32)
    at /tmp/.mount_HypergwCRUDA/resources/app.asar/node_modules/yaku/lib/yaku.js:575:38
    at flush (/tmp/.mount_HypergwCRUDA/resources/app.asar/node_modules/yaku/lib/yaku.js:478:17)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
(node:2500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## System

- OS (incl. version): Linux Mint 19.1
- Hypergraph Desktop version: 0.4.0 

## Additional context

This seems similar to the error from #156

**Comment by juliangruber** [comment]
Very weird that this is the same error you saw when running `npm start` on mac OS

**Comment by juliangruber** [comment]
This error happens while it tries to install the react devtools
